Repository Kuama-IT/android-document-scanner, pull requests merged in 2022-08, with the labels that each got.

#20 refactor (Corners) change data class implementation
  app/src/main/java/net/kuama/documentscanner/data/Corners.kt
  app/src/main/java/net/kuama/documentscanner/data/PaperSheetContoursResult.kt
  app/src/main/java/net/kuama/documentscanner/domain/FindPaperSheetContours.kt
  app/src/main/java/net/kuama/documentscanner/domain/PerspectiveTransform.kt
  app/src/main/java/net/kuama/documentscanner/extensions/MatOfPoint.kt
  app/src/main/java/net/kuama/documentscanner/presentation/PaperRect.kt
  app/src/main/java/net/kuama/documentscanner/utils/PerspectiveTransformUtils.kt
  app/src/main/java/net/kuama/documentscanner/utils/PointUtils.kt
  app/src/main/java/net/kuama/documentscanner/viewmodels/CropperModel.kt
  app/src/main/java/net/kuama/documentscanner/viewmodels/ScannerViewModel.kt
Labels: size/L

#19 feat (**) setup instrumented tests on CI
  .github/ci-gradle.properties
  .github/workflows/coverage.yaml
  app/build.gradle
  app/src/androidTest/java/net/kuama/documentscanner/ExampleInstrumentedTest.kt
  gradle.properties
  jacoco/modules.gradle
Labels: size/L

#23 feat (**) remove test workflow
  .github/workflows/coverage.yaml
Labels: size/M

#21 feat (MatOfPoint) test shape getter
  app/build.gradle
  app/src/androidTest/java/net/kuama/documentscanner/ExampleInstrumentedTest.kt
  app/src/androidTest/java/net/kuama/documentscanner/extensions/MatOfPointExtensionInstrumentedTest.kt
  app/src/androidTest/java/net/kuama/documentscanner/utils/TestUtils.kt
  app/src/main/java/net/kuama/documentscanner/extensions/MatOfPoint.kt
Labels: size/M

#22 feat (Context) test outputDirectory extension
  app/src/androidTest/java/net/kuama/documentscanner/extensions/ContextExtensionInstrumentedTest.kt
  app/src/main/java/net/kuama/documentscanner/extensions/Context.kt
  app/src/main/java/net/kuama/documentscanner/presentation/BaseScannerActivity.kt
  app/src/main/java/net/kuama/documentscanner/presentation/CropperActivity.kt
Labels: size/M

#27 add tests ci
  .github/workflows/tests.yaml
  app/src/androidTest/java/net/kuama/documentscanner/extensions/ContextExtensionInstrumentedTest.kt
  app/src/main/java/net/kuama/documentscanner/extensions/Context.kt
Labels: size/M

#25 fix (CropperActivity) sort corners after the user modified their position
  app/src/main/java/net/kuama/documentscanner/domain/UriToBitmap.kt
  app/src/main/java/net/kuama/documentscanner/presentation/BaseScannerActivity.kt
  app/src/main/java/net/kuama/documentscanner/presentation/CropperActivity.kt
  app/src/main/java/net/kuama/documentscanner/viewmodels/CropperModel.kt
  app/src/main/java/net/kuama/documentscanner/viewmodels/ScannerViewModel.kt
Labels: size/M

#28 feat (FindPaperSheetContours) add test
  .gitattributes
  app/src/androidTest/java/net/kuama/documentscanner/domain/FindPaperSheetContoursInstrumentedTest.kt
  app/src/androidTest/resources/document-picture.jpg
  app/src/main/java/net/kuama/documentscanner/viewmodels/CropperModel.kt
  images/crop.jpg
  images/detect.jpg
Labels: size/M

#26 fix (PointUtils) getSortedCorners was inverting bottom with top
  app/src/androidTest/java/net/kuama/documentscanner/utils/PointUtilsInstrumentedTest.kt
  app/src/main/java/net/kuama/documentscanner/utils/PointUtils.kt
Labels: size/M

#31 feat (**) merge unit test and android reports
  .github/workflows/code-style.yaml
  app/build.gradle
  app/src/androidTest/java/net/kuama/documentscanner/domain/InputStreamToBitmapInstrumentedTest.kt
  build.gradle
  jacoco/modules.gradle
  jacoco/project.gradle
Labels: size/L

#32 feat (**) add empty test for exceptions and enums
  KU-README.md
  app/src/androidTest/java/net/kuama/documentscanner/utils/PointUtilsInstrumentedTest.kt
  app/src/main/java/net/kuama/documentscanner/extensions/Context.kt
  app/src/main/java/net/kuama/documentscanner/extensions/View.kt
  app/src/main/java/net/kuama/documentscanner/presentation/CropperActivity.kt
  app/src/test/java/net/kuama/documentscanner/enums/EFlashStatusTest.kt
  app/src/test/java/net/kuama/documentscanner/enums/EOpenCvStatusTest.kt
  app/src/test/java/net/kuama/documentscanner/exceptions/MissingSquareExceptionTest.kt
  app/src/test/java/net/kuama/documentscanner/extensions/PointUtilsTest.kt
Labels: size/L

#33 fix (**) swap runBlocking to runTest for suspend functions
  app/build.gradle
  app/src/androidTest/java/net/kuama/documentscanner/domain/FindPaperSheetContoursInstrumentedTest.kt
  app/src/androidTest/java/net/kuama/documentscanner/domain/InputStreamToBitmapInstrumentedTest.kt
Labels: size/S

#36 feat (**) include reports manually into project
  .github/workflows/tests.yaml
  app/reports/testSuiteDebugJacocoReport.csv
  app/reports/testSuiteDebugJacocoReport.xml
  jacoco/modules.gradle
Labels: size/M

#34 refactor (OpenCvLoader) and add InstrumentedTest
  app/src/androidTest/java/net/kuama/documentscanner/data/OpenCVLoaderInstrumentedTest.kt
  app/src/main/java/net/kuama/documentscanner/data/OpenCVLoader.kt
Labels: size/M

#35 feat (**) add BaseUseCase for usecases that don't throw
  app/src/androidTest/java/net/kuama/documentscanner/domain/FindPaperSheetContoursInstrumentedTest.kt
  app/src/androidTest/java/net/kuama/documentscanner/domain/InputStreamToBitmapInstrumentedTest.kt
  app/src/androidTest/java/net/kuama/documentscanner/domain/PerspectiveTransformInstrumentedTest.kt
  app/src/androidTest/resources/blank.png
  app/src/androidTest/resources/file.txt
  app/src/main/java/net/kuama/documentscanner/domain/FindPaperSheetContours.kt
  app/src/main/java/net/kuama/documentscanner/domain/PerspectiveTransform.kt
  app/src/main/java/net/kuama/documentscanner/extensions/Bitmap.kt
  app/src/main/java/net/kuama/documentscanner/presentation/CropperActivity.kt
  app/src/main/java/net/kuama/documentscanner/support/UseCase.kt
  app/src/main/java/net/kuama/documentscanner/viewmodels/CropperModel.kt
  app/src/main/java/net/kuama/documentscanner/viewmodels/ScannerViewModel.kt
Labels: size/L

#38 fix (InpustreamToBitmap -> UriToBitmap) use Uri as input
  app/reports/testSuiteDebugJacocoReport.csv
  app/reports/testSuiteDebugJacocoReport.xml
  app/src/androidTest/java/net/kuama/documentscanner/domain/UriToBitmapInstrumentedTest.kt
  app/src/main/java/net/kuama/documentscanner/domain/UriToBitmap.kt
  app/src/main/java/net/kuama/documentscanner/viewmodels/CropperModel.kt
Labels: size/L
